#!/bin/sh

NODE_ENV='production'
NODE_APP='app.js'
APP_DIR='/home/thainokio/stranger-chat';
PID_FILE=$APP_DIR/process.pid
LOG_FILE=$APP_DIR/info.log
PORT=3001
NODE_EXEC='/opt/node/bin/node'
USER='thainokio'

# Source function library.
. /etc/rc.d/init.d/functions

###############

# REDHAT chkconfig header

# chkconfig: - 58 74
# description: thumb is the script for starting a node app stranger-chat on boot.
### BEGIN INIT INFO
# Provides: node
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop node
# Description: Node process for app
### END INIT INFO

start_app (){
    if [ -f $PID_FILE ]
    then
        echo "$PID_FILE exists, process is already running or crashed"
        exit 1
    else
        echo "Starting node app..."
        PORT=$PORT CWD=$APP_DIR NODE_ENV=$NODE_ENV daemon --user=$USER $NODE_EXEC $APP_DIR/$NODE_APP  1>$LOG_FILE 2>&1 &
        echo $! > $PID_FILE;
    fi
}

stop_app (){
    if [ ! -f $PID_FILE ]
    then
        echo "$PID_FILE does not exist, process is not running"
        exit 1
    else
        echo "Stopping $APP_DIR/$NODE_APP ..."
        echo "Killing `cat $PID_FILE`"
        kill `cat $PID_FILE`;
        rm -f $PID_FILE;
        echo "Node stopped"
    fi
}

case "$1" in
    start)
        start_app
    ;;

    stop)
        stop_app
    ;;

    restart)
        stop_app
        start_app
    ;;

    status)
        if [ -f $PID_FILE ]
        then
            PID=`cat $PID_FILE`
            if [ -z "`ps ef | awk '{print $1}' | grep "^$PID$"`" ]
            then
                echo "Chat stopped but pid file exists"
            else
                echo "Chat running with pid $PID"

            fi
        else
            echo "Chat stopped"
        fi
    ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
esac